load("//tools/bzl:classpath.bzl", "classpath_collector")

classpath_collector(
    name = "main_classpath_collect",
    testonly = 1,
    deps = [
        "//:changemessage__plugin_classpath_deps",
    ],
)
